version: '3.3'

services:
  web:
    build: .
    ports:
      - '3000:3000'
    hostname: web-server
    depends_on:
      - db
  db:
    container_name: mongo-dev
    image: 'mongo:3.6'
    ports:
      - '27017:27017'
    hostname: db-server
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - db-volume:/data/db
      - db-config-volume:/data/configdb
  mongo-express:
    image: 'mongo-express'
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo-dev
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
    depends_on:
      - db
volumes:
  db-volume:
  db-config-volume:
